{% set name = "django-followit" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-followit-{{ version }}.tar.gz
  sha256: 07a9ba15c85f5545c4da48bc63f74314a10265fdd3b123c990422d82bb8d5280

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django >=1.11,<3.0

test:
  source_files:
    - followit/tests/__init__.py
    - followit/tests/manage.py
    - followit/tests/models.py
    - followit/tests/runtests.py
    - followit/tests/settings.py
    - followit/tests/tests.py
  commands:
    - python -c "from django.conf import settings; settings.configure(); import followit"
    - python -c "import importlib.util; assert importlib.util.find_spec('followit')"
    - python followit/tests/runtests.py
about:
  home: https://github.com/ASKBOT/django-followit
  summary: A Django application that allows users to follow django model objects
  license: BSD-3-Clause
  license_file: followit/LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
